translation:
  locales: "%locales%"
  configs:
    app:
      dirs: [ "%kernel.project_dir%/assets", "%kernel.project_dir%/src" ]
      output_dir: "%kernel.project_dir%/translations"
      excluded_names: [ "*TestCase.php", "*Test.php" ]
      excluded_dirs: [ cache, data, logs ]
  webui:
    enabled: true